version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawler_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: go run cmd/main.go
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env

volumes:
  db-data:
